server {
    listen       80;
    server_name  localhost;

    # 配置静态文件访问
    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # 根据需要添加代理配置，例如：
    # location /api/ {
    #     proxy_pass http://your-backend-service:port/;
    # }
}